-- Create tables
CREATE TABLE STUDENT (
    REGNO VARCHAR2(10) PRIMARY KEY, 
    NAME VARCHAR2(20), 
    MAJOR VARCHAR2(20), 
    DOB DATE
);

CREATE TABLE COURSE (
    COURSENO NUMBER(10) PRIMARY KEY, 
    CNAME VARCHAR2(20), 
    DEPT VARCHAR2(30)
);

CREATE TABLE ENROLL (
    REGNO VARCHAR2(10) REFERENCES STUDENT, 
    COURSENO NUMBER(10) REFERENCES COURSE, 
    SEM NUMBER(5), 
    MARKS NUMBER(5)
);

CREATE TABLE TEXT (
    BKISBN NUMBER(13) PRIMARY KEY, 
    BOOK_TITLE VARCHAR2(20), 
    PUBLISHER VARCHAR2(50), 
    AUTHOR VARCHAR2(50)
);

CREATE TABLE BOOK_ADPT (
    COURSE_NO NUMBER(10) REFERENCES COURSE, 
    BKISBN NUMBER(13) REFERENCES TEXT, 
    SEM NUMBER(5)
);

-- Insert data into STUDENT
INSERT INTO STUDENT VALUES ('BCA101', 'RAMA L', 'BCA', TO_DATE('17-MAY-1989', 'DD-MON-YYYY'));
INSERT INTO STUDENT VALUES ('MCA101', 'BALA S', 'MCA', TO_DATE('12-JUN-1978', 'DD-MON-YYYY'));

-- Insert data into COURSE
INSERT INTO COURSE VALUES (101, 'COMPUTER', 'MCA');
INSERT INTO COURSE VALUES (102, 'COMPUTER', 'BCA');

-- Insert data into ENROLL
INSERT INTO ENROLL VALUES ('MCA101', 101, 3, 200);
INSERT INTO ENROLL VALUES ('BCA101', 102, 3, 400);

-- Insert data into TEXT
INSERT INTO TEXT VALUES (456, 'C PROGRAMMING', 'HIMALAYA', 'ADITHYA');

-- Insert data into BOOK_ADPT
INSERT INTO BOOK_ADPT VALUES (101, 456, 3);

-- Create view COMPDEPT
CREATE VIEW COMPDEPT AS 
    SELECT C.DEPT, C.COURSENO, T.BOOK_TITLE, T.BKISBN 
    FROM COURSE C
    JOIN BOOK_ADPT BA ON C.COURSENO = BA.COURSE_NO
    JOIN TEXT T ON BA.BKISBN = T.BKISBN
    WHERE DEPT = 'COMPUTER'
    ORDER BY T.BOOK_TITLE;

-- Query COMPDEPT view
SELECT * FROM COMPDEPT;

-- Query COMPDEPT view with condition
SELECT COURSENO, BKISBN, BOOK_TITLE 
FROM COMPDEPT 
WHERE DEPT IN (
    SELECT DEPT 
    FROM COMPDEPT 
    GROUP BY DEPT 
    HAVING COUNT(*) >= 2
);

-- Query courses and books with publisher 'HIMALAYA'
SELECT C.DEPT, T.BOOK_TITLE, T.PUBLISHER 
FROM COURSE C
JOIN BOOK_ADPT B ON C.COURSENO = B.COURSE_NO
JOIN TEXT T ON B.BKISBN = T.BKISBN
WHERE T.PUBLISHER = 'HIMALAYA';
