CREATE TABLE STUDENT (
    REGNO VARCHAR2(10) PRIMARY KEY, 
    NAME VARCHAR2(20), 
    MAJOR VARCHAR2(20), 
    DOB DATE
);

CREATE TABLE COURSE (
    COURSENO NUMBER(10) PRIMARY KEY, 
    CNAME VARCHAR2(20), 
    DEPT VARCHAR2(30)
);

CREATE TABLE ENROLL (
    REGNO VARCHAR2(10) REFERENCES STUDENT, 
    COURSENO NUMBER(10) REFERENCES COURSE, 
    SEM NUMBER(5), 
    MARKS NUMBER(5)
);

CREATE TABLE TEXT (
    BKISBN NUMBER(13) PRIMARY KEY, 
    BOOK_TITLE VARCHAR2(20), 
    PUBLISHER VARCHAR2(50), 
    AUTHOR VARCHAR2(50)
);

CREATE TABLE BOOK_ADPT (
    COURSE_NO NUMBER(10) REFERENCES COURSE, 
    BKISBN NUMBER(13) REFERENCES TEXT, 
    SEM NUMBER(5)
);

INSERT INTO STUDENT (REGNO, NAME, MAJOR, DOB) 
VALUES (:regno, :name, :major, TO_DATE(:dob, 'DD-MON-YYYY'));

INSERT INTO COURSE (COURSENO, CNAME, DEPT) 
VALUES (:courseno, :cname, :dept);

INSERT INTO ENROLL (REGNO, COURSENO, SEM, MARKS) 
VALUES (:regno, :courseno, :sem, :marks);

INSERT INTO TEXT (BKISBN, BOOK_TITLE, PUBLISHER, AUTHOR) 
VALUES (:bkisbn, :book_title, :publisher, :author);

INSERT INTO BOOK_ADPT (COURSE_NO, BKISBN, SEM) 
VALUES (:course_no, :bkisbn, :sem);


CREATE VIEW COMPDEPT AS 
    SELECT C.DEPT, C.COURSENO, T.BOOK_TITLE, T.BKISBN 
    FROM COURSE C
    JOIN BOOK_ADPT BA ON C.COURSENO = BA.COURSE_NO
    JOIN TEXT T ON BA.BKISBN = T.BKISBN
    WHERE DEPT = 'COMPUTER'
    ORDER BY T.BOOK_TITLE;

SELECT * FROM COMPDEPT;

SELECT COURSENO, BKISBN, BOOK_TITLE 
FROM COMPDEPT 
WHERE DEPT IN (
    SELECT DEPT 
    FROM COMPDEPT 
    GROUP BY DEPT 
    HAVING COUNT(*) >= 2
);

SELECT C.DEPT, T.BOOK_TITLE, T.PUBLISHER 
FROM COURSE C
JOIN BOOK_ADPT B ON C.COURSENO = B.COURSE_NO
JOIN TEXT T ON B.BKISBN = T.BKISBN
WHERE T.PUBLISHER = 'HIMALAYA';

-- DROP TABLE BOOK_ADPT CASCADE CONSTRAINTS;
-- DROP TABLE TEXT CASCADE CONSTRAINTS;
-- DROP TABLE ENROLL CASCADE CONSTRAINTS;
-- DROP TABLE COURSE CASCADE CONSTRAINTS;
-- DROP TABLE STUDENT CASCADE CONSTRAINTS;
