//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clancymendonca {
    public partial class Task2 {
        /// <summary>
        /// lblPrompt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPrompt;
        /// <summary>
        /// txtNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNumber;
        /// <summary>
        /// btnCheck control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCheck;
        /// <summary>
        /// lblResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResult;
    }
} 