//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clancymendonca {
    public partial class Task4 {
        /// <summary>
        /// lblPrompt1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPrompt1;
        /// <summary>
        /// txtNum1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNum1;
        /// <summary>
        /// lblPrompt2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPrompt2;
        /// <summary>
        /// txtNum2 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNum2;
        /// <summary>
        /// ddlOperation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlOperation;
        /// <summary>
        /// btnCalculate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCalculate;
        /// <summary>
        /// lblResult control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblResult;
    }
} 